FROM --platform=linux/amd64 python:3.14-bookworm

# RUN wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add -
# RUN echo "deb https://packages.adoptium.net/artifactory/deb bullseye /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list

RUN apt-get update && \
    apt-get install -y \
    vim-tiny \
    # gdal-bin \
    supervisor \
    # temurin-8-jdk \
    libpoppler-cpp-dev \
    pkg-config \
    libpq-dev \
    libgl1 \
    libssl-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /backend

COPY ./requirements.txt ./
RUN pip install -r requirements.txt --no-cache-dir
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["python3"] 
CMD ["manage.py", "runserver", "0.0.0.0:8000"]
